<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_edit Ship To</name>
   <tag></tag>
   <elementGuidId>238517f7-7310-4304-bb74-b1f17c83669a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='opc-sidebar']/div[2]/div/div/div/button</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.action.action-edit</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>8d151de4-94ae-40a1-87d8-9035f42485de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action action-edit</value>
      <webElementGuid>280ddca1-08c3-43fb-bfd9-a3bbd57178af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>click: back</value>
      <webElementGuid>06f7f6a3-1af8-4a5a-8081-525ef7133302</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
                edit
            </value>
      <webElementGuid>5e5db85c-3107-462f-935f-1a9b964a3b40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;opc-sidebar&quot;)/div[@class=&quot;opc-block-shipping-information&quot;]/div[@class=&quot;shipping-information&quot;]/div[@class=&quot;ship-to&quot;]/div[@class=&quot;shipping-information-title&quot;]/button[@class=&quot;action action-edit&quot;]</value>
      <webElementGuid>7cc41618-28ab-4cb9-ad2d-a965eaf3827f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='opc-sidebar']/div[2]/div/div/div/button</value>
      <webElementGuid>6807d5cc-93f9-47ae-bd09-cf5055781a70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ship To:'])[1]/following::button[1]</value>
      <webElementGuid>f92c4d55-ba00-447c-be1d-d4fe4ab04e69</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$7.00'])[1]/following::button[1]</value>
      <webElementGuid>0f9f87af-5b15-4a83-acd1-1017fb7eaf20</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div[2]/div/div/div/button</value>
      <webElementGuid>ec6e2b72-a22f-4e97-8cd0-e4e15a99db4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[(text() = '
                edit
            ' or . = '
                edit
            ')]</value>
      <webElementGuid>9a7cbcf3-e476-4c0d-9e1f-47e318b60bfc</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
