<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_billing-address-same-as-shipping</name>
   <tag></tag>
   <elementGuidId>619c426b-b530-4e70-b5ba-8d2a5ceca7fb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing-address-same-as-shipping-checkmo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing-address-same-as-shipping-checkmo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aa7affff-ddb3-489c-beb3-5633b59db4f5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>11bab7ee-fcac-4b81-946c-384593404251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing-address-same-as-shipping</value>
      <webElementGuid>e255e936-254a-445f-9193-c88a32a8173f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>checked: isAddressSameAsShipping, click: useShippingAddress, attr: {id: 'billing-address-same-as-shipping-' + getCode($parent)}</value>
      <webElementGuid>283ec706-b6e9-46db-88e3-0081aa609d95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing-address-same-as-shipping-checkmo</value>
      <webElementGuid>1c2d39b2-0505-4b89-a738-a340b3329084</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing-address-same-as-shipping-checkmo&quot;)</value>
      <webElementGuid>8f29c716-69a5-4490-92cc-4364287a34f8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing-address-same-as-shipping-checkmo']</value>
      <webElementGuid>68f574a1-b5df-4490-82f4-d9338230c4ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-method-load']/div/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>03196d64-9ff8-49bc-95b2-4fa9d1d995e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>54a15413-bbb8-402d-ac90-f57f32bcc125</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'billing-address-same-as-shipping' and @id = 'billing-address-same-as-shipping-checkmo']</value>
      <webElementGuid>dd47d64d-e13a-442a-8311-66ecc5fa24c4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
