<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_discount_code</name>
   <tag></tag>
   <elementGuidId>6eb800d9-c24e-4104-8336-41197cadd015</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='discount-code']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#discount-code</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>5852e433-18e4-4255-8a3b-2f887328697c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>d3e4d3a7-efe3-45e2-8608-f93f6bb81989</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>818f9649-b194-415e-a84d-bc2472f16e90</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>discount-code</value>
      <webElementGuid>2f107baf-5af7-450f-acca-631007fdca68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>discount_code</value>
      <webElementGuid>01515dd1-a490-40e5-8b09-d5ca8ce4dec6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{'required-entry':true}</value>
      <webElementGuid>8b1693f4-66a4-4204-9c8b-19e8356c8632</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: couponCode, attr:{disabled:isApplied() , placeholder: $t('Enter discount code')} </value>
      <webElementGuid>b6eed21a-76e9-4de5-b907-339c8fb81c2f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Enter discount code</value>
      <webElementGuid>8b6c5d5b-b752-46ea-a939-13d608f804ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;discount-code&quot;)</value>
      <webElementGuid>86e59287-c67a-425c-8ae8-cdb319caf13e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='discount-code']</value>
      <webElementGuid>81fd87c6-091e-48dc-a6a3-ac87a9a58aa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='discount-form']/div/div/div/input</value>
      <webElementGuid>65d20e4c-fc47-4af9-a815-3edb1e0bc06d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div[2]/form/div/div/div/input</value>
      <webElementGuid>d2c8e890-b396-43a2-8684-d0dc3f8ca3ba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @id = 'discount-code' and @name = 'discount_code' and @placeholder = 'Enter discount code']</value>
      <webElementGuid>bf64204e-e017-4d50-8779-755b9259e2d6</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
