<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>txt_empty_wishlist</name>
   <tag></tag>
   <elementGuidId>b920eef5-ed0d-43f6-a760-12b0a025e7c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//form[@id='wishlist-view-form']/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.message.info.empty</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5295a668-f912-43a3-b328-3ace9aea799e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>message info empty</value>
      <webElementGuid>46b04718-dd4f-40a0-acbf-4cea04747e99</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>You have no items in your wish list.</value>
      <webElementGuid>b5449bd8-5237-45df-b420-573344035958</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;wishlist-view-form&quot;)/div[@class=&quot;message info empty&quot;]</value>
      <webElementGuid>7f37f718-053c-42f3-aa35-02e7fd76b3c1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='wishlist-view-form']/div</value>
      <webElementGuid>69ac15d2-ce3f-4637-9c91-5ad32b12b7d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='My Wish List'])[4]/following::div[3]</value>
      <webElementGuid>893a5893-d046-43b9-a37b-fde74a4ffcbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[4]/following::div[9]</value>
      <webElementGuid>bcf521d4-bf1e-4ccb-b3fe-cb2f633d2989</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/preceding::div[2]</value>
      <webElementGuid>7bc45c0b-a359-490e-9a79-1f247a32e577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//main/div[2]/div/form/div</value>
      <webElementGuid>69febfc0-b7ec-4d00-b33e-08d42881ad07</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'You have no items in your wish list.' or . = 'You have no items in your wish list.')]</value>
      <webElementGuid>e8f016d1-87f0-405d-ad43-2bdfa5e9f5d4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
