<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_Registered Customers</name>
   <tag></tag>
   <elementGuidId>08ef17b1-31a8-452e-aea6-e29e0f58710b</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#block-customer-login-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//strong[@id='block-customer-login-heading'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>7a9c53be-db4f-412e-8f90-4a36cdfd3512</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>block-customer-login-heading</value>
      <webElementGuid>5404d1b8-f96a-4b96-9407-5f22edaf227e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>659f8757-e768-4455-a6c3-f9c22887ad3d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>f4d4aa19-5841-4733-807d-3ca5796877b7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Registered Customers</value>
      <webElementGuid>76f0acef-41ce-40ea-9135-6af8ff5f9f40</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;block block-customer-login&quot;]/div[@class=&quot;block-title&quot;]/strong[@id=&quot;block-customer-login-heading&quot;]</value>
      <webElementGuid>0828ea33-15d4-4506-8c65-60d72a4f2139</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//strong[@id='block-customer-login-heading']</value>
      <webElementGuid>c8ff931e-8209-4a4f-9d33-1a70ee6230ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[2]/div/div/strong</value>
      <webElementGuid>9495b915-3ab4-4928-b9f5-bf1ee0757c8c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Customer Login'])[2]/following::strong[1]</value>
      <webElementGuid>763576a3-a30f-448e-840d-522a48307096</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an Account'])[2]/following::strong[1]</value>
      <webElementGuid>71966483-ff90-4b9e-9548-69629bf3b5b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='If you have an account, sign in with your email address.'])[1]/preceding::strong[1]</value>
      <webElementGuid>eedab306-134c-4b7f-9bcb-7d76c05f1041</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Email'])[1]/preceding::strong[1]</value>
      <webElementGuid>fb070cd7-b70d-4f6c-bb0d-e66e1d4d0d59</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Registered Customers']/parent::*</value>
      <webElementGuid>6f9ecdf0-46e9-4a79-aeb3-ebf846da70b8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div/div/strong</value>
      <webElementGuid>4d1ac88f-255f-4c07-b062-6c64c7ffe267</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[@id = 'block-customer-login-heading' and (text() = 'Registered Customers' or . = 'Registered Customers')]</value>
      <webElementGuid>84cb2ff3-c4b0-4ffa-aa41-e26ead63794f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
