<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_New Customers</name>
   <tag></tag>
   <elementGuidId>be61f5a1-660d-4554-990a-ac62b56a7f34</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#block-new-customer-heading</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//strong[@id='block-new-customer-heading'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>e9fee2c8-2ab0-4812-a828-e93e2c69db22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>block-new-customer-heading</value>
      <webElementGuid>108583d3-f3bc-4d50-bd60-26b2181b5e51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>heading</value>
      <webElementGuid>961e0171-90a3-49ac-ae44-d9fee35d29df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-level</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>4be38b28-a81f-4ffb-b344-0deb57757931</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>New Customers</value>
      <webElementGuid>cd681ae4-6fbd-4c4a-92fd-8c37da491340</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;login-container&quot;]/div[@class=&quot;block block-new-customer&quot;]/div[@class=&quot;block-title&quot;]/strong[@id=&quot;block-new-customer-heading&quot;]</value>
      <webElementGuid>86255b94-527c-4627-a389-b17b3c8165d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//strong[@id='block-new-customer-heading']</value>
      <webElementGuid>719f8b9a-926c-46dd-9de3-e0454973c6d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[2]/div[2]/div/strong</value>
      <webElementGuid>a08b9872-3b31-459e-b00d-19c2b37cff4a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Forgot Your Password?'])[1]/following::strong[1]</value>
      <webElementGuid>8632e6d2-5775-4a38-8903-c3c8dd69dd61</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign In'])[3]/following::strong[1]</value>
      <webElementGuid>3a8cf762-39ab-4660-9337-4b2ab114976c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create an Account'])[3]/preceding::strong[1]</value>
      <webElementGuid>48afa436-9ef4-4a3e-b296-ebd4d8198428</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Try Demo Customer Access'])[1]/preceding::strong[1]</value>
      <webElementGuid>cfaccb7f-6e90-4333-bb67-5fc1133e0b1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='New Customers']/parent::*</value>
      <webElementGuid>39a92caf-6117-4cd1-a1bd-ffa8c11b8a93</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/div[2]/div[2]/div/strong</value>
      <webElementGuid>ef727068-4208-44fc-8917-c570d262fbfc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[@id = 'block-new-customer-heading' and (text() = 'New Customers' or . = 'New Customers')]</value>
      <webElementGuid>8c74f967-5c75-4850-89d2-a6317b006262</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
