<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_Men Tanks</name>
   <tag></tag>
   <elementGuidId>24454c21-9d56-4231-b54c-08388b2655c6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//h1[@id='page-title-heading']/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.base</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2f1bab78-d809-46c8-bd1f-a32bc826e6ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>base</value>
      <webElementGuid>473d154e-a7ea-4998-aa17-1612ec1c1916</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-ui-id</name>
      <type>Main</type>
      <value>page-title-wrapper</value>
      <webElementGuid>48186506-3e93-4444-8223-e917dc7d598d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tanks</value>
      <webElementGuid>fccc18a4-cd18-4551-8e68-4c5893e9264d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;page-title-heading&quot;)/span[@class=&quot;base&quot;]</value>
      <webElementGuid>18873e40-78cb-4b3b-a6c9-c9ab068286d8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//h1[@id='page-title-heading']/span</value>
      <webElementGuid>3ed751d6-c85a-4ff5-af7b-2734cdc18211</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tanks'])[2]/following::span[1]</value>
      <webElementGuid>b7257f61-8e92-4848-8b38-c0b6b035e47b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tops'])[3]/following::span[1]</value>
      <webElementGuid>63c6f392-0734-4828-9e94-5fd2f9416d10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='View as'])[1]/preceding::span[1]</value>
      <webElementGuid>fbaf2788-e944-4deb-8c5c-0b812f90266f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Grid'])[1]/preceding::span[1]</value>
      <webElementGuid>d53e1e27-1b5e-4531-863d-44b9118939e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//h1/span</value>
      <webElementGuid>e3e80184-d06b-4472-9325-ff07ae29ba11</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tanks' or . = 'Tanks')]</value>
      <webElementGuid>94bf8b7f-3a40-47be-807f-c04d8abbf545</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
