<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errormsg_Qty_greaterthan0</name>
   <tag></tag>
   <elementGuidId>fc51ffa6-5a12-4213-b7f7-5d162347a0dd</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-245437-qty-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class = 'mage-error' and (text() = 'Please enter a number greater than 0 in this field.' or . = 'Please enter a number greater than 0 in this field.')])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>4c9080e0-16f9-43d7-817a-e974177193e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>cart-245437-qty</value>
      <webElementGuid>d20dcd56-9c34-4a2b-80d2-55f501918947</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>0d5a6ade-b829-4ad8-ad67-a90cfb77842a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mage-error</value>
      <webElementGuid>c5e2d8a2-4586-4b4b-b131-b071c48e9f12</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-245437-qty-error</value>
      <webElementGuid>2b49ac9d-c06c-4498-afed-adfd40969726</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a number greater than 0 in this field.</value>
      <webElementGuid>725d4f18-978e-440b-a24e-b400b2bf9edf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-245437-qty-error&quot;)</value>
      <webElementGuid>f834a7f4-cfc0-4adb-b3b3-81540756cea6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='cart-245437-qty-error']</value>
      <webElementGuid>c65ac58e-d972-490e-af92-396f46442550</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='shopping-cart-table']/tbody/tr/td[3]/div/div/label/div</value>
      <webElementGuid>7fbb9c34-d1c2-4ced-b1ef-b03f67e22cd4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[12]/following::div[1]</value>
      <webElementGuid>21529384-703a-40c8-9314-8ac9be6562a4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$49.00'])[2]/following::div[3]</value>
      <webElementGuid>8eafffff-09f1-4d93-bc43-81a69b602213</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$196.00'])[1]/preceding::div[1]</value>
      <webElementGuid>de14a2c5-a049-4aed-9ae0-d341660ab383</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Move to Wishlist'])[1]/preceding::div[2]</value>
      <webElementGuid>15742f36-d5d6-4a29-a412-53b2bfdba99e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter a number greater than 0 in this field.']/parent::*</value>
      <webElementGuid>593ac90c-8c32-4450-ad1f-d8f87b34b33f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/div</value>
      <webElementGuid>769bb133-08ba-4149-aefd-07af9b80cd46</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'cart-245437-qty-error' and (text() = 'Please enter a number greater than 0 in this field.' or . = 'Please enter a number greater than 0 in this field.')]</value>
      <webElementGuid>7477a35e-3af3-4232-b596-9f6c51cb1040</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
