<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>expand_Apply Discount Code</name>
   <tag></tag>
   <elementGuidId>28ed6625-64e1-4e3b-bd63-fddbd77ed910</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#block-discount > div.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//div[@id='block-discount']/div)[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a482620a-d28d-4089-9e56-4a857827252a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>fa1807f5-f0d3-49ce-8886-8c08a6f9df54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>title</value>
      <webElementGuid>36c38dfd-1384-4dfb-ba60-78f4950ab00f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>tab</value>
      <webElementGuid>14fdd488-f048-4835-ad2c-b9955fc6c0a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-selected</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>34eaf62f-bf47-4911-9af0-9b88820c3dc6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-expanded</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>20dcf360-2b2d-43f5-a6cd-855ffce545b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>323fdc9c-b326-40fe-b1bc-5fe80889592d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Apply Discount Code
</value>
      <webElementGuid>942ee454-0521-46a5-b0c9-4015e5310ab2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;block-discount&quot;)/div[@class=&quot;title&quot;]</value>
      <webElementGuid>30d375b1-ff31-4065-9adc-7154b5c5c42f</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='block-discount']/div</value>
      <webElementGuid>1b853829-5a06-4469-b734-51b65c673cbd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Update Shopping Cart'])[1]/following::div[4]</value>
      <webElementGuid>b28c2f99-2019-43d6-a11f-cb23c4787e1c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Clear Shopping Cart'])[1]/following::div[4]</value>
      <webElementGuid>b6ee17f3-a63c-44ae-9e52-c9f3cb3eac0a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Enter discount code'])[1]/preceding::div[1]</value>
      <webElementGuid>e4856f5c-a1df-4b03-853e-1311582134d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div[3]/div/div</value>
      <webElementGuid>b3d77c6e-ae72-4ab7-a60c-ffb83230b6a1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = '
Apply Discount Code
' or . = '
Apply Discount Code
')]</value>
      <webElementGuid>aa4ee320-6f10-4513-b786-f3dbe794ebfb</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
