<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>img_Loading</name>
   <tag></tag>
   <elementGuidId>ead554e7-a215-4cde-8d93-b0322ec8669a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>img[alt=&quot;Loading...&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='cart-totals']/div/div/div/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>2674cbdc-c1f2-448f-bcdd-97cd97479c76</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/pub/static/version1678540400/frontend/Magento/luma/en_US/images/loader-1.gif</value>
      <webElementGuid>ef8f1eeb-4720-4800-a60d-6e3adcc6c9d3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>alt</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>6770800b-7981-4206-9dac-fb191d98888d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Loading...</value>
      <webElementGuid>3472528c-9913-4993-b08f-c2dba6439861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-totals&quot;)/div[@class=&quot;table-wrapper _block-content-loading&quot;]/div[@class=&quot;loading-mask&quot;]/div[@class=&quot;loader&quot;]/img[1]</value>
      <webElementGuid>b1b12cc0-1630-4785-9b75-c4c12bb17bea</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='cart-totals']/div/div/div/img</value>
      <webElementGuid>38292c1a-d668-43f4-a27b-11a38ec5b4d5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[@alt='Loading...']</value>
      <webElementGuid>24d4136b-3c64-41e1-bedf-9f15fac9cc0f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div/img</value>
      <webElementGuid>2e651d0a-128a-44a4-a117-0d35ade2dbba</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento.softwaretestingboard.com/pub/static/version1678540400/frontend/Magento/luma/en_US/images/loader-1.gif' and @alt = 'Loading...' and @title = 'Loading...']</value>
      <webElementGuid>83eacd55-6f7c-4180-a09b-02e225230010</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
