<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Qty first product</name>
   <tag></tag>
   <elementGuidId>a4243586-af1c-4298-b075-4d195efd2028</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#cart-245437-qty</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@type = 'number' and @class = 'input-text qty' and @data-role = 'cart-item-qty'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>bc96b208-a7d6-4e21-9d51-6a0d4bb80f2c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>cart-245437-qty</value>
      <webElementGuid>d2236c05-5548-431a-8fd0-b8ecc74bf8d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>cart[245437][qty]</value>
      <webElementGuid>60a60ab8-b772-4539-a036-3777667060cc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-cart-item-id</name>
      <type>Main</type>
      <value>WP13-28-Blue</value>
      <webElementGuid>52521200-816e-4634-9105-c66cecd66c23</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>24bbd32a-df45-41c5-918a-5e7253a3a9dd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5010db20-df48-4829-9505-bb3c4a48e0c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>4</value>
      <webElementGuid>5ff2b607-c634-4a6e-842c-19aebee8094e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>step</name>
      <type>Main</type>
      <value>any</value>
      <webElementGuid>d5823ff0-2625-4f9e-a51b-1b60678b31bc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Qty</value>
      <webElementGuid>4232165b-ae90-443a-a1cc-ded44d7fddeb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text qty</value>
      <webElementGuid>682375ab-6d13-4790-8ea9-bffcf931a6b4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{required:true,'validate-greater-than-zero':true}</value>
      <webElementGuid>83960605-1914-40d7-abde-7e328f33b230</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>cart-item-qty</value>
      <webElementGuid>58211888-306f-4645-a6b2-7ca943e3b6aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;cart-245437-qty&quot;)</value>
      <webElementGuid>460b4359-d17b-4fa7-9d8e-a64221be60fc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='cart-245437-qty']</value>
      <webElementGuid>2b277b59-9e2e-4326-b6c2-4c07f2257fb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='shopping-cart-table']/tbody/tr/td[3]/div/div/label/input</value>
      <webElementGuid>282a5a35-9fe2-445b-8019-4fde6b5524d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label/input</value>
      <webElementGuid>2f1084bf-6e8c-4946-8729-0d2425c09c8f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'cart-245437-qty' and @name = 'cart[245437][qty]' and @type = 'number' and @title = 'Qty']</value>
      <webElementGuid>94ed77d1-3501-4cf2-84f2-e44380d3513c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
