<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>title_Summary</name>
   <tag></tag>
   <elementGuidId>64108dee-a527-4814-96d9-091e5d7d8275</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>strong.summary.title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[3]/div/div[2]/div/strong</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>strong</value>
      <webElementGuid>d81cb1d8-12c1-4ad4-83ad-78cd5a63aaa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>summary title</value>
      <webElementGuid>48b9510c-f5f0-40a2-b3ca-edab236560e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Summary</value>
      <webElementGuid>2d1e21cc-c3e8-4dee-b006-5f0abbb75f0d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;cart-container&quot;]/div[@class=&quot;cart-summary&quot;]/strong[@class=&quot;summary title&quot;]</value>
      <webElementGuid>9af8bb75-8f2a-44e3-8c63-42f2a09405e5</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[2]/div/strong</value>
      <webElementGuid>74005aad-3f81-42b7-873e-b4550f2a82ac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Shopping Cart'])[2]/following::strong[1]</value>
      <webElementGuid>cdcf66e5-0400-405a-b4c6-2e15d26e7f41</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sign Out'])[4]/following::strong[1]</value>
      <webElementGuid>38c6c72f-e7c4-4215-b999-3618d9c3c0d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimate Shipping and Tax'])[1]/preceding::strong[1]</value>
      <webElementGuid>9d65e180-79d9-4ab0-aac0-15083b4171e9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Estimate Shipping and Tax'])[2]/preceding::strong[2]</value>
      <webElementGuid>9ed4e5f2-6b9a-4574-a3ba-706a82b2d8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Summary']/parent::*</value>
      <webElementGuid>5d73a43c-11c3-4446-af71-2c8db5d8632c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div[2]/div/strong</value>
      <webElementGuid>9958599e-c93b-48dc-bf29-13b065560edf</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//strong[(text() = 'Summary' or . = 'Summary')]</value>
      <webElementGuid>14d858cd-49bc-4ee6-af9e-53c51923927e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
