<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>4stars_rating</name>
   <tag></tag>
   <elementGuidId>5f07419c-4329-40ba-97d1-0a3c49864fd9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#Rating_4_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//label[@id='Rating_4_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>label</value>
      <webElementGuid>ad88218e-561e-4e55-902a-1b1a2bdd6208</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>rating-4</value>
      <webElementGuid>daf6970a-f7fd-49a2-8790-faf4aead1425</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>Rating_4</value>
      <webElementGuid>f3d4148f-f7b2-4b9b-b0ef-d9b3bb39b475</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>4 stars</value>
      <webElementGuid>c547287f-9573-47e6-b486-c6151c5fb284</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>Rating_4_label</value>
      <webElementGuid>c7ae7282-ea00-4273-a609-5ce7612786a6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
4 stars
</value>
      <webElementGuid>6a1663f3-ba27-434f-b3f0-7d14c0fe6a71</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;Rating_4_label&quot;)</value>
      <webElementGuid>2f7c5b20-4e78-46e6-8529-a9f112ccf5f6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//label[@id='Rating_4_label']</value>
      <webElementGuid>49879933-bad6-4eea-a1cc-3a043c6fdc31</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-review-table']/div/div/label[4]</value>
      <webElementGuid>b5fdb0c2-4df1-49fc-9f6a-e73556a0c3a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Rating'])[4]/following::label[4]</value>
      <webElementGuid>37e7d6b7-e526-4841-918e-b71b0a77541b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Your Rating'])[1]/following::label[5]</value>
      <webElementGuid>49a70803-5919-413a-834e-7c64f7282e91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Nickname'])[1]/preceding::label[2]</value>
      <webElementGuid>7dc764a1-17ed-40c8-9d04-c39a59d7b198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Summary'])[1]/preceding::label[3]</value>
      <webElementGuid>da7a8017-1a90-40f7-9213-1d1557f8d714</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//label[4]</value>
      <webElementGuid>9e10a85f-8f96-4df8-94ae-e5a091a341c4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//label[@title = '4 stars' and @id = 'Rating_4_label' and (text() = '
4 stars
' or . = '
4 stars
')]</value>
      <webElementGuid>b218c413-9729-4475-b25f-380d91bd3746</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
