<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add to Compare</name>
   <tag></tag>
   <elementGuidId>de6a8362-1a06-4f8a-97fc-93a1b98481cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.action.tocompare</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div/div[5]/div/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>fe5dbcc3-645d-449a-a61e-2b37a363f25e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#</value>
      <webElementGuid>3827a8a4-712f-4317-9219-b74c21388635</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-post</name>
      <type>Main</type>
      <value>{&quot;action&quot;:&quot;https:\/\/magento.softwaretestingboard.com\/catalog\/product_compare\/add\/&quot;,&quot;data&quot;:{&quot;product&quot;:&quot;1412&quot;,&quot;uenc&quot;:&quot;aHR0cHM6Ly9tYWdlbnRvLnNvZnR3YXJldGVzdGluZ2JvYXJkLmNvbS9nYWJyaWVsbGUtbWljcm8tc2xlZXZlLXRvcC5odG1s&quot;}}</value>
      <webElementGuid>34180d9e-8201-4d8e-bab4-83ed41e0ec9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-role</name>
      <type>Main</type>
      <value>add-to-links</value>
      <webElementGuid>76c20b9c-e8ea-4428-80db-69f1199a2eaa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action tocompare</value>
      <webElementGuid>e004708c-9e48-44a9-87b1-58e1991dd4f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add to Compare</value>
      <webElementGuid>654f9723-4d39-479c-91d6-9cbfdf9cbfd1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;product-info-main&quot;]/div[@class=&quot;product-social-links&quot;]/div[@class=&quot;product-addto-links&quot;]/a[@class=&quot;action tocompare&quot;]</value>
      <webElementGuid>860f6cce-89a5-4db1-90f6-ecc3c96c557d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div/div[5]/div/a[2]</value>
      <webElementGuid>5621a977-e543-4216-b933-13ee95c70c91</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Wish List'])[1]/following::a[1]</value>
      <webElementGuid>fb99c71c-2bc8-4bc3-b725-13b06b496cc4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[1]/following::a[2]</value>
      <webElementGuid>a13b141e-f99f-4905-9d84-e9ea35fa20dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to the end of the images gallery'])[1]/preceding::a[2]</value>
      <webElementGuid>680107b1-5854-4581-9d8c-9afbae614e9d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#')])[8]</value>
      <webElementGuid>2274705d-868b-4cdc-af22-5ab47cb507c3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/a[2]</value>
      <webElementGuid>f47d7157-f8e0-4cb0-9134-c209a530583d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#' and (text() = 'Add to Compare' or . = 'Add to Compare')]</value>
      <webElementGuid>171b1888-a039-4f94-a880-96c061f02c1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
