<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Add Your Review</name>
   <tag></tag>
   <elementGuidId>98becc86-9e10-49fb-aa89-e41bf081f09d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.action.add</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[2]/div/div/div[2]/div[2]/a[2]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>b9d103fa-4366-4e95-b4c9-22c9322ea09c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>action add</value>
      <webElementGuid>4ae64f70-b798-416e-8c84-f1b3fb842071</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/bella-tank.html#review-form</value>
      <webElementGuid>09290e8b-adc9-4cc5-b72e-b53f2968f332</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Add Your Review</value>
      <webElementGuid>384c8b27-a3d8-4b07-ac7b-c74a7558aced</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;product-info-main&quot;]/div[@class=&quot;product-reviews-summary&quot;]/div[@class=&quot;reviews-actions&quot;]/a[@class=&quot;action add&quot;]</value>
      <webElementGuid>0a62d47b-143f-47fa-a681-71c8496b304e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div/div[2]/div[2]/a[2]</value>
      <webElementGuid>b423d098-b528-4397-8d45-20b3955856af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Add Your Review')]</value>
      <webElementGuid>03c361fb-bd10-4389-a8d8-f873fea206e4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Reviews'])[1]/following::a[1]</value>
      <webElementGuid>48eca75e-afdb-4d3b-b28d-1ba861ff26ed</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='As low as'])[1]/preceding::a[1]</value>
      <webElementGuid>23e81cdf-cbfe-4599-aa74-0fdc21d5709f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='$29.00'])[1]/preceding::a[1]</value>
      <webElementGuid>7b305789-cc21-4b0e-8996-8306e459cabb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Add Your Review']/parent::*</value>
      <webElementGuid>b68779d2-f2dd-431c-a7d9-97bd137b817f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://magento.softwaretestingboard.com/bella-tank.html#review-form')]</value>
      <webElementGuid>020862ae-0b23-4e1b-b732-900a2a023aa2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//a[2]</value>
      <webElementGuid>dee9fed2-152b-452a-a437-c74f72dc3c54</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://magento.softwaretestingboard.com/bella-tank.html#review-form' and (text() = 'Add Your Review' or . = 'Add Your Review')]</value>
      <webElementGuid>8033818a-0158-47e4-a516-8b3d20806d8a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
