<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Details</name>
   <tag></tag>
   <elementGuidId>8af87a95-be75-4607-ab43-bda7beb5eea6</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-label-description-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tab-label-description-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>77d8f059-dfd4-44d7-8a82-e167a5a6f71e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data switch</value>
      <webElementGuid>bd5c0c50-d773-486d-83d3-434e6cbf5e22</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>92cff427-ed69-4051-9183-b2feed65eff1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>trigger</value>
      <webElementGuid>2a2ca237-394f-41e1-8225-9e66d50ff169</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#description</value>
      <webElementGuid>a0e60953-3dfa-4d48-9fe1-1226d02dde28</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-label-description-title</value>
      <webElementGuid>8072c0e7-7c25-4e5d-8377-8588c23268db</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Details </value>
      <webElementGuid>67d0e38e-2e33-4854-a99d-21c8b8454194</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-label-description-title&quot;)</value>
      <webElementGuid>452a13f1-d9a6-421d-a24d-05c4174b8d22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tab-label-description-title']</value>
      <webElementGuid>33f4189f-c75c-4f10-ba98-f2a606fcaf27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-label-description']/a</value>
      <webElementGuid>cb9023ec-c771-4b67-afb1-4d031047d5bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Details')]</value>
      <webElementGuid>f124a59d-c870-4a71-a288-d71a8f67a9d9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to the beginning of the images gallery'])[1]/following::a[2]</value>
      <webElementGuid>78bcf5d7-87c9-4048-98c8-bce3761d76f6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Skip to the end of the images gallery'])[1]/following::a[3]</value>
      <webElementGuid>73745b8b-ebe1-4613-b522-60ac3d388c5a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Information'])[1]/preceding::a[1]</value>
      <webElementGuid>30d9d246-8fb9-45a4-b676-5f095a300d74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='More Information'])[2]/preceding::a[2]</value>
      <webElementGuid>afcddf55-4582-4a6b-82d1-ccdb71fc726d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Details']/parent::*</value>
      <webElementGuid>e1004fbf-f571-4743-89c9-248054eb9425</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, '#description')]</value>
      <webElementGuid>210db7a6-6ee6-406e-b401-68fb0cb2100b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/a</value>
      <webElementGuid>26d24e6a-0a28-46f9-b7ab-93651922f9af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#description' and @id = 'tab-label-description-title' and (text() = '
Details ' or . = '
Details ')]</value>
      <webElementGuid>d1feaadc-998d-4fa4-b879-2d929d85442b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
