<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_User Reviews</name>
   <tag></tag>
   <elementGuidId>292938b4-cf7e-4b0b-b2d6-65101f857592</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#tab-label-reviews-title</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='tab-label-reviews-title']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3f83c6e2-48d6-41c7-8d33-ca365f0e0141</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>data switch</value>
      <webElementGuid>7e4f9340-3e5c-4d8f-8efa-6ca68b677a6a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>17ae05e7-483c-417c-9307-9c9eea6d9451</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-toggle</name>
      <type>Main</type>
      <value>trigger</value>
      <webElementGuid>ab78cd9b-d876-4c77-ad96-c14d434bc5ef</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>#reviews</value>
      <webElementGuid>68d77a8b-b4de-40ee-953b-60c72913f293</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>tab-label-reviews-title</value>
      <webElementGuid>e4852cc3-fe58-468c-afa9-144f9adb1fa8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>
Reviews 3 </value>
      <webElementGuid>d8e4afd7-2b26-4562-9fb0-f9159e39d336</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;tab-label-reviews-title&quot;)</value>
      <webElementGuid>95b39418-000f-45fe-b7b0-839882ad4cd8</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='tab-label-reviews-title']</value>
      <webElementGuid>bac2829d-17ae-473b-91c0-f7f542fb9008</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='tab-label-reviews']/a</value>
      <webElementGuid>6f1a9cf2-6be9-44f2-9df1-c81571f26ea0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Indoor, Warm'])[1]/following::a[1]</value>
      <webElementGuid>6ca5e5f9-643a-4745-b371-9c6fd5b9bcea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Climate'])[1]/following::a[1]</value>
      <webElementGuid>35d8bc98-b980-4daf-b0c3-2a1faca3d451</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Write Your Own Review'])[1]/preceding::a[1]</value>
      <webElementGuid>45e42fad-f124-4589-808c-a5ccf2fbe07c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)=concat('You', &quot;'&quot;, 're reviewing:')])[1]/preceding::a[1]</value>
      <webElementGuid>c2cae54b-77e6-45dc-b30a-93a132799457</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, '#reviews')])[2]</value>
      <webElementGuid>e46b3b1e-c072-435a-9b70-71462a38adc8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/a</value>
      <webElementGuid>76fc274a-5ef9-4474-bb9f-fe29f5a5a972</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = '#reviews' and @id = 'tab-label-reviews-title' and (text() = '
Reviews 3 ' or . = '
Reviews 3 ')]</value>
      <webElementGuid>ba7eb18c-9ef6-4f69-8adc-48fdbf4d5e98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
