<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>errormsg_qty greater than 0</name>
   <tag></tag>
   <elementGuidId>a5605b07-f2aa-4203-ac30-7111a8508046</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qty-error</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='qty-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>a9f2b375-f849-4433-a959-5e2f73e3d79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>qty</value>
      <webElementGuid>abab3444-3fec-4250-ab93-12382e50af93</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>2e415c5f-1b55-4a47-9ac9-664bd9a78e9c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mage-error</value>
      <webElementGuid>14d82c34-ed0d-4e46-9ce5-5293ac8da9d6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qty-error</value>
      <webElementGuid>cfbf36ff-f6ad-4d1f-9ba6-742745cdacc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Please enter a quantity greater than 0.</value>
      <webElementGuid>9146fc50-a080-410e-93fb-a26e2fe902af</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qty-error&quot;)</value>
      <webElementGuid>072026ef-32f7-4503-bb46-7054102c6921</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='qty-error']</value>
      <webElementGuid>c3bf38ca-1d71-4c5a-9e32-d4541b2fa8fc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='product_addtocart_form']/div[2]/div/div/div/div/div</value>
      <webElementGuid>da78ac4f-5920-4a66-bd1e-7b54c618e1de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Qty'])[2]/following::div[2]</value>
      <webElementGuid>0c7c65a6-c0a4-4bb9-bb29-2c7be7e8da10</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='This is a required field.'])[2]/following::div[6]</value>
      <webElementGuid>b87e45c0-4efa-4693-97da-533edbea2ae6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Cart'])[1]/preceding::div[1]</value>
      <webElementGuid>069595ee-2faa-4350-91c9-d8644fc8cee4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Add to Wish List'])[1]/preceding::div[3]</value>
      <webElementGuid>e7d8ab4b-6f8f-46c0-b82c-6c36c3c8934e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Please enter a quantity greater than 0.']/parent::*</value>
      <webElementGuid>7911c4cf-1115-4384-b4ea-34be5326d323</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div[2]/div/div/div/div/div</value>
      <webElementGuid>0d3e6d91-6523-49cc-af37-5b73b70c1979</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'qty-error' and (text() = 'Please enter a quantity greater than 0.' or . = 'Please enter a quantity greater than 0.')]</value>
      <webElementGuid>6b48985d-ef91-42df-bee1-3c1e298dd515</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
