<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_nickname</name>
   <tag></tag>
   <elementGuidId>2256dc9a-efc1-47fc-b1ab-e87b4cb96d65</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#nickname_field</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='nickname_field']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3c586eda-68f9-4cd2-ab41-d292f48b7182</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a9d00e67-9b22-4626-8f30-877924d74a3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>nickname</value>
      <webElementGuid>81d179f2-4b22-458c-9e10-fdec34b860c6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>nickname_field</value>
      <webElementGuid>650ec18b-ce3c-4b30-9e95-48da43203545</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>d9877542-25d6-4410-a478-1ce82fec404c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-validate</name>
      <type>Main</type>
      <value>{required:true}</value>
      <webElementGuid>ade85654-14c5-4ac4-ac8a-24b2444d2ca5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>value: nickname()</value>
      <webElementGuid>d8313b49-1727-43b1-bad2-af548be0d850</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>26a23527-fa59-447b-bc89-b87dea573b42</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;nickname_field&quot;)</value>
      <webElementGuid>ded00845-5d7c-4147-b365-b02d55a68807</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='nickname_field']</value>
      <webElementGuid>c7ebc7e9-f19c-41a1-b2d9-ce625af1bf7c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='review-form']/fieldset/div/div/input</value>
      <webElementGuid>509d5ab8-dcae-4810-a049-83e95b1223d7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//fieldset/div/div/input</value>
      <webElementGuid>91f3070a-0dbe-4cc8-8387-3ff009247c1d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'text' and @name = 'nickname' and @id = 'nickname_field']</value>
      <webElementGuid>807e9a85-1df6-492e-8dc8-53b0761f4b6e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
