<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>options_label_allsize</name>
   <tag></tag>
   <elementGuidId>f42adc15-4a2e-417b-b342-74772e4d5cab</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.swatch-attribute-options.clearfix</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class = 'swatch-attribute-options clearfix'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>6c7cdd5d-f804-4ddd-a84b-83370533f82c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>42d7fef6-622f-483e-833f-4e05a33adc9b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-invalid</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>c88b90f0-7f6c-41e4-bab3-274c3c621cb2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>67f2c6fe-76e7-4933-9a3a-668bf332bceb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>listbox</value>
      <webElementGuid>ebda427c-7e3c-4465-8b01-a2faa1fcfb68</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-labelledby</name>
      <type>Main</type>
      <value>option-label-size-143</value>
      <webElementGuid>0dde1251-bca3-47a7-bfcd-8a4bed4b4c1a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-attribute-options clearfix</value>
      <webElementGuid>835bca0c-e52a-41b7-9aec-1b3d5ad1b95a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>XSSMLXL</value>
      <webElementGuid>8a8d3fde-908e-4951-9a18-73fcd8508dbf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;product-options-wrapper&quot;)/div[@class=&quot;fieldset&quot;]/div[@class=&quot;swatch-opt&quot;]/div[@class=&quot;swatch-attribute size&quot;]/div[@class=&quot;swatch-attribute-options clearfix&quot;]</value>
      <webElementGuid>02daccef-3c50-46ef-a062-ba73324e5ec4</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div/div</value>
      <webElementGuid>01ea066e-f4cd-4c2d-a876-48765d5f55b1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Size'])[1]/following::div[1]</value>
      <webElementGuid>11504d76-5934-48f6-838b-414e3b92664e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='WS12'])[1]/following::div[6]</value>
      <webElementGuid>521fc274-6029-473b-93cf-559914006639</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div</value>
      <webElementGuid>9d57b9ac-315c-4937-a810-fac5678b7fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'XSSMLXL' or . = 'XSSMLXL')]</value>
      <webElementGuid>c5dbc4b1-2554-46d1-84c6-1b628b55c58f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
