<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>required_size</name>
   <tag></tag>
   <elementGuidId>68549b1b-90b5-4959-af13-d4a7ac0b3838</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='super_attribute[143]-error']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>c252b235-8b9b-4bb4-a88c-89756c0ac059</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>for</name>
      <type>Main</type>
      <value>super_attribute[143]</value>
      <webElementGuid>84a0875e-fa53-4e50-aead-659f0dc82d0b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>generated</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>63cf25fd-29d9-4637-a9f4-db16e0d83b81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mage-error</value>
      <webElementGuid>a44eb1e4-4df5-4d37-97cf-4530310552b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>super_attribute[143]-error</value>
      <webElementGuid>d5b7f9eb-815f-45ee-be94-4bc6a6045445</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>This is a required field.</value>
      <webElementGuid>276dcc4b-0f32-49ee-bb6b-0e6a16eb5de4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;super_attribute[143]-error&quot;)</value>
      <webElementGuid>3dffb2e5-94ef-4fdf-bd89-68f6670ee2d2</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='super_attribute[143]-error']</value>
      <webElementGuid>40d3fd74-584e-4de4-b37f-e1a2b3344eae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div/div[2]</value>
      <webElementGuid>f4acbf3b-ae1c-4891-8fc2-cc3b5ee5adf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XL'])[1]/following::div[1]</value>
      <webElementGuid>0753cee5-e693-4655-818e-af5b3dd79689</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L'])[1]/following::div[2]</value>
      <webElementGuid>cb851262-cf11-4bdf-9a1c-0aaadddefafc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Color'])[1]/preceding::div[1]</value>
      <webElementGuid>f3cff831-a8fb-49aa-8375-319196e5ecb6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Purple'])[1]/preceding::div[1]</value>
      <webElementGuid>63bafc11-fe7d-48e8-8d45-46151ed588c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='This is a required field.']/parent::*</value>
      <webElementGuid>c1c1371f-362e-4ee3-978f-1c7755f07a48</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div[2]</value>
      <webElementGuid>507a896b-ee79-495e-bf77-6e126f856a78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'super_attribute[143]-error' and (text() = 'This is a required field.' or . = 'This is a required field.')]</value>
      <webElementGuid>72eefefe-9e14-4f48-8b35-907a8466f9c9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
