<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>slide_to_firstimage</name>
   <tag></tag>
   <elementGuidId>eb49668b-321b-4cb8-a8bc-55ecd9007eb1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>div.fotorama__arr__arr</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class = 'fotorama__arr__arr'])[1]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>b89dcc3a-e1ed-44ef-8d00-50f750beddbd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>fotorama__arr__arr</value>
      <webElementGuid>d3064e35-f638-4030-abf7-477db72a9606</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;product media&quot;]/div[@class=&quot;gallery-placeholder&quot;]/div[@class=&quot;fotorama-item fotorama fotorama1689012277872&quot;]/div[@class=&quot;fotorama__wrap fotorama__wrap--css3 fotorama__wrap--slide fotorama__wrap--toggle-arrows&quot;]/div[@class=&quot;fotorama__stage&quot;]/div[@class=&quot;fotorama__arr fotorama__arr--prev&quot;]/div[@class=&quot;fotorama__arr__arr&quot;]</value>
      <webElementGuid>14fec62b-69d9-4593-af5c-11c7d407928b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[2]/div/div[2]/div[2]/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>fc5ab33a-0c99-4770-98d9-42f110bd000b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div[2]/div[2]/div/div[2]/div</value>
      <webElementGuid>465650f9-8f66-4ca7-83e6-c3acff793354</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
