<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>select_third_size</name>
   <tag></tag>
   <elementGuidId>cf4046b2-acaf-42c3-8154-5f887f44fa5e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#option-label-size-143-item-168</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>(//*[@class = 'swatch-option text'])[3]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>5fe5e480-a28c-427e-bf5e-73e524978955</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>swatch-option text</value>
      <webElementGuid>22ec4051-5704-42ac-bc21-06b117290eb4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>option-label-size-143-item-168</value>
      <webElementGuid>107f9c9b-c2bf-490a-8376-bd8b4aca2370</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>index</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>3e5d89e4-e1f9-483f-87ba-fd8ce6210154</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-checked</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>b274a1ea-6ed4-4bfe-b2d0-9eaec75fedb7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-describedby</name>
      <type>Main</type>
      <value>option-label-size-143</value>
      <webElementGuid>569ce892-266e-4496-b1ae-4d3ebcee5281</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>0c7d06d4-4a18-429d-9925-44ffdbe7bd6b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-type</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>449d2339-a1da-47fc-bf51-5c001f3a875e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-id</name>
      <type>Main</type>
      <value>168</value>
      <webElementGuid>49087771-0a9b-428b-9951-de726d9f4dd4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-label</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>290a00a4-bdc7-4f8d-8409-e94184718c51</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>e2673fa1-4391-4733-86b5-3667d6d29d64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>option-tooltip-value</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>6019da23-b68e-480c-83bb-ff674cb184e2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>option</value>
      <webElementGuid>54ae8ffa-0630-4655-a738-411cf1aaf5a9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-width</name>
      <type>Main</type>
      <value>110</value>
      <webElementGuid>8f81bd2b-a118-4ff6-a9fc-de8b9100c7d4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>thumb-height</name>
      <type>Main</type>
      <value>90</value>
      <webElementGuid>935e443b-82b9-4fdb-86e9-daf4181e29ce</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>M</value>
      <webElementGuid>2694f30e-9d47-4e13-8693-ebf37fd58ee5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;option-label-size-143-item-168&quot;)</value>
      <webElementGuid>082069ec-8df3-4c1f-bf1e-9ff68322d784</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//div[@id='option-label-size-143-item-168']</value>
      <webElementGuid>a4518df6-a1d0-49bb-94c5-9de70e2f2ebe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='product-options-wrapper']/div/div/div/div/div[3]</value>
      <webElementGuid>7ef1ec37-47ce-4dd3-8656-b9ed7d9d8433</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='S'])[2]/following::div[1]</value>
      <webElementGuid>8a4aac03-6a32-4b5e-b460-f77d7170160b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XS'])[2]/following::div[2]</value>
      <webElementGuid>2e88059a-bf21-4007-8b55-6db7ef7ea911</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='L'])[1]/preceding::div[1]</value>
      <webElementGuid>80799aa1-3080-4ec0-bc4a-8cfd1200abb1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='XL'])[1]/preceding::div[2]</value>
      <webElementGuid>44eedb2e-6e24-42af-bb57-c4ae3c5d9256</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='M']/parent::*</value>
      <webElementGuid>00f87574-15d4-4bae-8873-9950a4e89b3c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//form/div/div/div/div/div/div[3]</value>
      <webElementGuid>2d06549f-2884-4d64-aa1e-2962a484abf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[@id = 'option-label-size-143-item-168' and (text() = 'M' or . = 'M')]</value>
      <webElementGuid>6130575a-3753-4fd5-a180-021388d06d98</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
