<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Women Shorts</name>
   <tag></tag>
   <elementGuidId>f6f3082b-74af-49ac-8060-d535e84d83b1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='ui-id-16']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#ui-id-16</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>dccc7cf9-c910-4b80-99ba-b4062a290f84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/women/bottoms-women/shorts-women.html</value>
      <webElementGuid>57a6849c-13da-4a63-8448-ced4dadb4ef2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>ui-id-16</value>
      <webElementGuid>35367a81-14de-4f8e-8a2d-9edca33d6783</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ui-corner-all</value>
      <webElementGuid>11468087-dd7f-494f-b50e-4611f7feffa3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>-1</value>
      <webElementGuid>6b6c7a22-6f42-4e1b-b545-1adb2707a08a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>menuitem</value>
      <webElementGuid>3df609a3-fb88-4173-b33a-36d9b4c3332b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Shorts</value>
      <webElementGuid>19043171-0a58-4c4a-9422-4b9d645153b1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;ui-id-16&quot;)</value>
      <webElementGuid>dc20a976-a84f-49d3-b24e-7f3c918c9499</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='ui-id-16']</value>
      <webElementGuid>6f95f859-9e13-48c7-8068-e3b1d05011ce</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//ul[@id='ui-id-2']/li[2]/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>03ae3a16-ec05-4e65-ac59-7b8c08ccd1d0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pants'])[1]/following::a[1]</value>
      <webElementGuid>64225e7f-c47e-461e-bd7d-3a12e8158dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Bottoms'])[1]/following::a[2]</value>
      <webElementGuid>9485b554-4d30-4c6c-9203-ec8c61e4ce3f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Men'])[1]/preceding::a[1]</value>
      <webElementGuid>02ff9169-6a9b-48cb-85c1-9a5a8531d805</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://magento.softwaretestingboard.com/women/bottoms-women/shorts-women.html')]</value>
      <webElementGuid>5f78c0dd-cf55-4fe5-82c2-4163b7febb0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[2]/ul/li[2]/ul/li[2]/a</value>
      <webElementGuid>b1bc7891-6811-4a9d-a75b-0fa35dc1d292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://magento.softwaretestingboard.com/women/bottoms-women/shorts-women.html' and @id = 'ui-id-16' and (text() = 'Shorts' or . = 'Shorts')]</value>
      <webElementGuid>0e72aa39-4d4d-442e-b7aa-55073244f6ec</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
