<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>hyperlinkimg_pants</name>
   <tag></tag>
   <elementGuidId>9284b2b4-4df0-4693-bba4-240b557f818d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.block-promo.home-pants</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//main[@id='maincontent']/div[3]/div/div[2]/div/div/a/img</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>839ce93b-bfc4-4942-ab66-477c849ad7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>src</name>
      <type>Main</type>
      <value>https://magento.softwaretestingboard.com/pub/media/wysiwyg/home/home-pants.jpg</value>
      <webElementGuid>a3ed4196-4625-41d6-9c33-95b84eb2f6de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;maincontent&quot;)/div[@class=&quot;columns&quot;]/div[@class=&quot;column main&quot;]/div[@class=&quot;widget block block-static-block&quot;]/div[@class=&quot;blocks-promo&quot;]/div[@class=&quot;block-promo-wrapper block-promo-hp&quot;]/a[@class=&quot;block-promo home-pants&quot;]/img[1]</value>
      <webElementGuid>869cf642-5cba-48c0-908a-a05e67679d42</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//main[@id='maincontent']/div[3]/div/div[2]/div/div/a/img</value>
      <webElementGuid>bdd8fa19-5edf-40ad-83ee-d8f2f2c74875</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:img</name>
      <type>Main</type>
      <value>//img[contains(@src,'https://magento.softwaretestingboard.com/pub/media/wysiwyg/home/home-pants.jpg')]</value>
      <webElementGuid>e767d2e8-9e81-4fb4-b5e4-3631f1105275</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/a/img</value>
      <webElementGuid>fba7aabe-0e90-4c4b-835b-fa7de3191901</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//img[@src = 'https://magento.softwaretestingboard.com/pub/media/wysiwyg/home/home-pants.jpg']</value>
      <webElementGuid>b8c257ae-14aa-413e-835a-16bf93e5c1e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
