<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_billing-save-in-address-book-checkmo</name>
   <tag></tag>
   <elementGuidId>0ab29e3f-2d07-4871-a3fc-3f286df4977f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing-save-in-address-book-checkmo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing-save-in-address-book-checkmo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>040a6dab-8197-44d9-8222-64dd2eb67c4d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>7fa58ee5-ea3e-444f-84fb-c06aec3df36a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>c10fffb8-272a-4fbe-b8b9-cf9f7524d75a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>checked: saveInAddressBook, attr: {id: 'billing-save-in-address-book-' + getCode($parent)}</value>
      <webElementGuid>5db0858f-403b-4c2d-b853-d2ddf29d7d27</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing-save-in-address-book-checkmo</value>
      <webElementGuid>da5ae391-6489-4ade-8e91-9246a7c9aaa0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing-save-in-address-book-checkmo&quot;)</value>
      <webElementGuid>5553dd06-786d-4270-9f87-1d6327ffec18</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing-save-in-address-book-checkmo']</value>
      <webElementGuid>1079ef0c-4ecd-4723-b866-d32f693762c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-method-load']/div/div/div[2]/div[2]/div[2]/div/fieldset/div[2]/div/form/fieldset/div[10]/input</value>
      <webElementGuid>100c06a7-30a3-424d-a48e-5d8b359487d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[10]/input</value>
      <webElementGuid>d0fec808-0476-4798-93e5-5eeef1ee632e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @id = 'billing-save-in-address-book-checkmo']</value>
      <webElementGuid>910bdbf5-a8d7-470c-9309-413966eb8400</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
