<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_order_billing-address-same-as-shipping</name>
   <tag></tag>
   <elementGuidId>fe34469b-bd20-4a4b-be2d-7c3f7e2529e7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='billing-address-same-as-shipping-checkmo']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#billing-address-same-as-shipping-checkmo</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>15a3f92f-b059-49b4-b10c-84b29876b79e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>checkbox</value>
      <webElementGuid>bd034159-b1d2-4617-ba87-6394ca826026</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>billing-address-same-as-shipping</value>
      <webElementGuid>6242f013-c228-4817-9f80-a9c8e7ce979a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-bind</name>
      <type>Main</type>
      <value>checked: isAddressSameAsShipping, click: useShippingAddress, attr: {id: 'billing-address-same-as-shipping-' + getCode($parent)}</value>
      <webElementGuid>3bfa3492-7d4a-40ae-99a1-83c30949c6e5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>billing-address-same-as-shipping-checkmo</value>
      <webElementGuid>43c9d51b-dc60-47f9-b71d-f7933f81817b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;billing-address-same-as-shipping-checkmo&quot;)</value>
      <webElementGuid>a6198a38-0391-4ba0-9fea-8bef15119829</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='billing-address-same-as-shipping-checkmo']</value>
      <webElementGuid>aff334ab-60df-464d-84e3-3298e7df4bf9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='checkout-payment-method-load']/div/div/div[2]/div[2]/div[2]/div/div/input</value>
      <webElementGuid>36b95af2-d520-4ce6-a5bc-342b4f55c4fd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/input</value>
      <webElementGuid>14a04b23-4a48-45f4-8855-b132bb39eebb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'checkbox' and @name = 'billing-address-same-as-shipping' and @id = 'billing-address-same-as-shipping-checkmo']</value>
      <webElementGuid>c7fa4bf8-670a-49b3-b6f0-e2488e2ea3df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
