<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>total_price_inminicart</name>
   <tag></tag>
   <elementGuidId>09b288aa-d411-4582-abf7-3a275deec201</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='minicart-content-wrapper']/div[2]/div[2]/div/span/span</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>span.price</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fc557594-b4a2-4380-b393-8cef4dfab752</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>price</value>
      <webElementGuid>25dc8d0e-028c-4966-bc3c-4d1f52d70305</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>$171.00</value>
      <webElementGuid>2c372330-a96d-47ac-8134-3fc91c6ed923</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;minicart-content-wrapper&quot;)/div[@class=&quot;block-content&quot;]/div[@class=&quot;subtotal&quot;]/div[@class=&quot;amount price-container&quot;]/span[@class=&quot;price-wrapper&quot;]/span[@class=&quot;price&quot;]</value>
      <webElementGuid>10f48278-f66e-4f52-8832-a22a0dee594b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='minicart-content-wrapper']/div[2]/div[2]/div/span/span</value>
      <webElementGuid>66754462-d8b9-45fa-9bec-c4d172db33c1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cart Subtotal'])[1]/following::span[2]</value>
      <webElementGuid>651ce2bb-f77f-44f9-9b63-b3ffff21c017</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Items in Cart'])[1]/following::span[4]</value>
      <webElementGuid>fdf2da9e-63e6-481d-a302-dc04a5a5a258</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Proceed to Checkout'])[1]/preceding::span[1]</value>
      <webElementGuid>a5ecc20c-3738-471a-a0d1-915e42a1eeb3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Recently added item(s)'])[1]/preceding::span[1]</value>
      <webElementGuid>a1d1fd6b-de65-4f80-bcd7-1aa80e62b8ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='$171.00']/parent::*</value>
      <webElementGuid>018593c4-8fbb-42bf-bb6e-49715613a243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/span/span</value>
      <webElementGuid>f961dd69-88c9-43b8-9512-dcdb6f95bb9b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = '$171.00' or . = '$171.00')]</value>
      <webElementGuid>18b0784d-f74a-435e-a1d0-7693558bffb3</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
